# Generated by Django 2.2.12 on 2023-02-15 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventry', '0002_auto_20230215_0550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientasset',
            name='is_active',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
