# Generated by Django 2.2.12 on 2023-02-15 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventry', '0003_auto_20230215_0551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientasset',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='clientasset',
            name='is_dispatch',
            field=models.BooleanField(default=False),
        ),
    ]
