# Generated by Django 2.2.12 on 2023-02-15 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventry', '0006_auto_20230215_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientasset',
            name='date_of_dispatch',
            field=models.DateTimeField(blank=True, default='', null=True),
        ),
    ]
