# Generated by Django 2.2.12 on 2023-02-15 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventry', '0009_auto_20230215_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientasset',
            name='configuration',
            field=models.CharField(max_length=250),
        ),
    ]
