# Generated by Django 2.2.12 on 2023-02-15 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventry', '0010_auto_20230215_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='in_voices',
            field=models.BooleanField(default=False),
        ),
    ]
