# Generated by Django 2.2.12 on 2023-02-15 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventry', '0011_asset_in_voices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='in_voices',
        ),
        migrations.AddField(
            model_name='asset',
            name='in_voice',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='---', max_length=20),
        ),
    ]
