# Generated by Django 2.2.12 on 2023-02-15 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventry', '0012_auto_20230215_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientasset',
            name='client_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
