# Generated by Django 2.2.12 on 2023-02-16 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventry', '0013_clientasset_client_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignasset',
            name='date_of_assign',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
