# Generated by Django 4.1.5 on 2023-02-16 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventry', '0016_alter_asset_id_alter_assettype_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='price_per_asset',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
