# Generated by Django 4.1.5 on 2023-02-20 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventry', '0017_asset_price_per_asset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='price_per_asset',
        ),
    ]
