# Generated by Django 4.1.5 on 2023-02-20 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventry', '0018_remove_asset_price_per_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='serial_number',
            field=models.CharField(default='', max_length=50),
        ),
    ]
