# Generated by Django 4.1.5 on 2023-02-20 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventry', '0019_asset_serial_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='invoice_number',
            field=models.CharField(default='', max_length=30),
        ),
    ]
