# Generated by Django 4.1.5 on 2023-02-21 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventry', '0021_alter_asset_purchase_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='payment_status',
            field=models.CharField(choices=[('due', 'due'), ('done', 'done')], default='', max_length=20),
        ),
    ]
