# Generated by Django 4.1.5 on 2023-02-21 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventry', '0023_alter_asset_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientasset',
            name='serial_number',
            field=models.CharField(default='', max_length=50),
        ),
    ]
