# Generated by Django 4.1.5 on 2023-02-22 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventry', '0024_clientasset_serial_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='operating_system',
            field=models.CharField(blank=True, choices=[('UBUNTU', 'ubuntu'), ('MAC OS', 'mac os'), ('WINDOW', 'window'), ('HACKINTOSH', 'hackintosh')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='processor',
            field=models.CharField(blank=True, choices=[('i3', 'i3'), ('i5', 'i5'), ('i7', 'i7'), ('i9', 'i9'), ('i10', 'i10')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='ram',
            field=models.CharField(blank=True, choices=[('4GB', '4GB'), ('6GB', '6GB'), ('8GB', '8GB'), ('16GB', '16GB'), ('32GB', '32GB'), ('64GB', '64GB')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='ssd',
            field=models.CharField(blank=True, choices=[('120', '120'), ('250', '250'), ('256', '256'), ('500', '500')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='storage',
            field=models.CharField(blank=True, choices=[('16', '16'), ('32', '32'), ('64', '64'), ('128', '128'), ('256', '256'), ('512', '512')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='serial_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
