# Generated by Django 4.1.5 on 2023-02-23 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventry', '0027_clientasset_operating_system_clientasset_processor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientasset',
            name='project_owner',
            field=models.CharField(max_length=50),
        ),
    ]
