# Generated by Django 4.1.5 on 2023-02-23 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventry', '0028_alter_clientasset_project_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='is_assign',
            field=models.BooleanField(default=False),
        ),
    ]
