# Generated by Django 4.1.7 on 2023-03-09 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventry', '0029_asset_is_assign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientasset',
            name='date_of_dispatch',
            field=models.DateField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='clientasset',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
