# Generated by Django 4.1.7 on 2023-03-16 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventry', '0030_alter_clientasset_date_of_dispatch_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignasset',
            name='have_asset',
        ),
        migrations.RemoveField(
            model_name='assignasset',
            name='serial_number',
        ),
        migrations.AlterField(
            model_name='assignasset',
            name='date_of_assign',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
