# Generated by Django 4.1.7 on 2023-03-20 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventry', '0032_alter_clientasset_date_of_dispatch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignasset',
            name='date_of_assign',
            field=models.DateField(blank=True, null=True),
        ),
    ]
