# Generated by Django 3.2.11 on 2023-08-03 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventry', '0035_alter_assignasset_date_of_assign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='technology_name',
            field=models.CharField(blank=True, choices=[('Python', 'Python'), ('Quality_Analyst', 'Quality_Analyst'), ('Angular', 'Angular'), ('React', 'React'), ('IOS', 'IOS'), ('Flutter', 'Flutter'), ('Blockchain', 'Blockchain'), ('Android', 'Android'), ('SEO', 'SEO'), ('React-Native', 'React-Native'), ('Node', 'Node'), ('Business_Development', 'Business_Development'), ('Web_Design', 'Web_Design'), ('other', 'other')], max_length=20, null=True),
        ),
    ]
