# Generated by Django 3.2.11 on 2023-08-04 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventry', '0036_alter_employee_technology_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date_of_joining',
            field=models.DateField(blank=True, null=True),
        ),
    ]
