# Generated by Django 3.2.11 on 2023-08-04 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventry', '0037_alter_employee_date_of_joining'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='vendor_name',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
