# Generated by Django 3.2.11 on 2023-08-04 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventry', '0038_vendor_vendor_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='vendor_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
